name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build application
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/

      - name: Check for Vercel secrets
        id: check-secrets
        run: |
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ] && [ -n "${{ secrets.VERCEL_ORG_ID }}" ] && [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "secrets-available=true" >> $GITHUB_OUTPUT
          else
            echo "secrets-available=false" >> $GITHUB_OUTPUT
            echo "⚠️ Vercel deployment secrets not configured. Skipping deployment."
          fi

      - name: Deploy to Vercel (Production)
        if: steps.check-secrets.outputs.secrets-available == 'true' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel (Preview)
        if: steps.check-secrets.outputs.secrets-available == 'true' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
        id: vercel-preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--no-wait'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Comment PR with deployment URL
        if: github.event_name == 'pull_request' && steps.vercel-preview.outputs.preview-url
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview Deployment Ready!**
              \n\n📱 **URL:** ${{ steps.vercel-preview.outputs.preview-url }}
              \n\nThis preview will be automatically updated when you push new commits to this PR.`
            });

  build-status:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Build Success
        if: needs.build.result == 'success'
        run: echo "✅ Build completed successfully!"
        
      - name: Build Failed
        if: needs.build.result == 'failure'
        run: |
          echo "❌ Build failed!"
          exit 1
